name: Build and Push Docker Image

on:
  push:
    branches:
      - v8

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Load environment variables from .env
        uses: falti/dotenv-action@v1.1.4
        with:
          path: .env

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push custom Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: build/Dockerfile.custom
          push: true
          tags: |
            ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_REPOSITORY }}:latest-custom
            ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_REPOSITORY }}:${{ github.sha }}-custom
          build-args: |
            GOLANG_VERSION=${{ env.GOLANG_VERSION }}
            GOTENBERG_VERSION=${{ env.GOTENBERG_VERSION }}
            GOTENBERG_USER_GID=${{ env.GOTENBERG_USER_GID }}
            GOTENBERG_USER_UID=${{ env.GOTENBERG_USER_UID }}
            NOTO_COLOR_EMOJI_VERSION=${{ env.NOTO_COLOR_EMOJI_VERSION }}
            PDFTK_VERSION=${{ env.PDFTK_VERSION }}
